### ISSUE TITLE
Invalid result syntax produces cryptic errors "expected 'x', found 'y'"

### ISSUE THREAD

**Issue by stephensearles** [str1ngs/jflect#9]
I got super confused when running some json through this and got errors like:

```
2016/03/30 09:45:26 1:35: expected ';', found '-' (and 1 more errors)
```
and
```
2016/03/30 09:54:33 1:28: expected '}', found 'INT' 0
```

Turns out, these are caused by hyphens in the json key name and key names beginning with numbers.

```
$ echo '{"some-key": "foo"}' | jflect
2016/03/30 10:01:16 1:32: expected ';', found '-' (and 1 more errors)
```

```
$ echo '{"0": "foo"}' | jflect
2016/03/30 09:54:33 1:28: expected '}', found 'INT' 0
```

It's clear to me now why these are errors: they result in types that are invalid Go syntax. I'm not sure there's an obvious way to handle all the cases around things like these errors, but perhaps an error message tweak could at least make the cause of the problem more apparent.

**Comment by str1ngs** [comment]
Thanks for the bug report. I 'll start by making the error message clearer. Right now I'm just returning go errors from the stdlib as is. 

I think "some-key" is fixable by removing the hyphen and then preducing camel case for clarity. So some-key would look like SomeKey . 

In the case of the numeric field name, I might just leave it as is but  instead, return a more friendly error. I think regardless of  what jflect does, those field names would want to  be manually changed regardless.
